package com.wzy.ems.pojo;

import java.util.ArrayList;
import java.util.List;

public class CommuteExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table commute
     *
     * @mbg.generated Mon Feb 08 11:23:38 CST 2021
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table commute
     *
     * @mbg.generated Mon Feb 08 11:23:38 CST 2021
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table commute
     *
     * @mbg.generated Mon Feb 08 11:23:38 CST 2021
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commute
     *
     * @mbg.generated Mon Feb 08 11:23:38 CST 2021
     */
    public CommuteExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commute
     *
     * @mbg.generated Mon Feb 08 11:23:38 CST 2021
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commute
     *
     * @mbg.generated Mon Feb 08 11:23:38 CST 2021
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commute
     *
     * @mbg.generated Mon Feb 08 11:23:38 CST 2021
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commute
     *
     * @mbg.generated Mon Feb 08 11:23:38 CST 2021
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commute
     *
     * @mbg.generated Mon Feb 08 11:23:38 CST 2021
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commute
     *
     * @mbg.generated Mon Feb 08 11:23:38 CST 2021
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commute
     *
     * @mbg.generated Mon Feb 08 11:23:38 CST 2021
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commute
     *
     * @mbg.generated Mon Feb 08 11:23:38 CST 2021
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commute
     *
     * @mbg.generated Mon Feb 08 11:23:38 CST 2021
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commute
     *
     * @mbg.generated Mon Feb 08 11:23:38 CST 2021
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table commute
     *
     * @mbg.generated Mon Feb 08 11:23:38 CST 2021
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andCommutenoIsNull() {
            addCriterion("commuteno is null");
            return (Criteria) this;
        }

        public Criteria andCommutenoIsNotNull() {
            addCriterion("commuteno is not null");
            return (Criteria) this;
        }

        public Criteria andCommutenoEqualTo(Integer value) {
            addCriterion("commuteno =", value, "commuteno");
            return (Criteria) this;
        }

        public Criteria andCommutenoNotEqualTo(Integer value) {
            addCriterion("commuteno <>", value, "commuteno");
            return (Criteria) this;
        }

        public Criteria andCommutenoGreaterThan(Integer value) {
            addCriterion("commuteno >", value, "commuteno");
            return (Criteria) this;
        }

        public Criteria andCommutenoGreaterThanOrEqualTo(Integer value) {
            addCriterion("commuteno >=", value, "commuteno");
            return (Criteria) this;
        }

        public Criteria andCommutenoLessThan(Integer value) {
            addCriterion("commuteno <", value, "commuteno");
            return (Criteria) this;
        }

        public Criteria andCommutenoLessThanOrEqualTo(Integer value) {
            addCriterion("commuteno <=", value, "commuteno");
            return (Criteria) this;
        }

        public Criteria andCommutenoIn(List<Integer> values) {
            addCriterion("commuteno in", values, "commuteno");
            return (Criteria) this;
        }

        public Criteria andCommutenoNotIn(List<Integer> values) {
            addCriterion("commuteno not in", values, "commuteno");
            return (Criteria) this;
        }

        public Criteria andCommutenoBetween(Integer value1, Integer value2) {
            addCriterion("commuteno between", value1, value2, "commuteno");
            return (Criteria) this;
        }

        public Criteria andCommutenoNotBetween(Integer value1, Integer value2) {
            addCriterion("commuteno not between", value1, value2, "commuteno");
            return (Criteria) this;
        }

        public Criteria andCnameIsNull() {
            addCriterion("cname is null");
            return (Criteria) this;
        }

        public Criteria andCnameIsNotNull() {
            addCriterion("cname is not null");
            return (Criteria) this;
        }

        public Criteria andCnameEqualTo(String value) {
            addCriterion("cname =", value, "cname");
            return (Criteria) this;
        }

        public Criteria andCnameNotEqualTo(String value) {
            addCriterion("cname <>", value, "cname");
            return (Criteria) this;
        }

        public Criteria andCnameGreaterThan(String value) {
            addCriterion("cname >", value, "cname");
            return (Criteria) this;
        }

        public Criteria andCnameGreaterThanOrEqualTo(String value) {
            addCriterion("cname >=", value, "cname");
            return (Criteria) this;
        }

        public Criteria andCnameLessThan(String value) {
            addCriterion("cname <", value, "cname");
            return (Criteria) this;
        }

        public Criteria andCnameLessThanOrEqualTo(String value) {
            addCriterion("cname <=", value, "cname");
            return (Criteria) this;
        }

        public Criteria andCnameLike(String value) {
            addCriterion("cname like", value, "cname");
            return (Criteria) this;
        }

        public Criteria andCnameNotLike(String value) {
            addCriterion("cname not like", value, "cname");
            return (Criteria) this;
        }

        public Criteria andCnameIn(List<String> values) {
            addCriterion("cname in", values, "cname");
            return (Criteria) this;
        }

        public Criteria andCnameNotIn(List<String> values) {
            addCriterion("cname not in", values, "cname");
            return (Criteria) this;
        }

        public Criteria andCnameBetween(String value1, String value2) {
            addCriterion("cname between", value1, value2, "cname");
            return (Criteria) this;
        }

        public Criteria andCnameNotBetween(String value1, String value2) {
            addCriterion("cname not between", value1, value2, "cname");
            return (Criteria) this;
        }

        public Criteria andClocalIsNull() {
            addCriterion("clocal is null");
            return (Criteria) this;
        }

        public Criteria andClocalIsNotNull() {
            addCriterion("clocal is not null");
            return (Criteria) this;
        }

        public Criteria andClocalEqualTo(String value) {
            addCriterion("clocal =", value, "clocal");
            return (Criteria) this;
        }

        public Criteria andClocalNotEqualTo(String value) {
            addCriterion("clocal <>", value, "clocal");
            return (Criteria) this;
        }

        public Criteria andClocalGreaterThan(String value) {
            addCriterion("clocal >", value, "clocal");
            return (Criteria) this;
        }

        public Criteria andClocalGreaterThanOrEqualTo(String value) {
            addCriterion("clocal >=", value, "clocal");
            return (Criteria) this;
        }

        public Criteria andClocalLessThan(String value) {
            addCriterion("clocal <", value, "clocal");
            return (Criteria) this;
        }

        public Criteria andClocalLessThanOrEqualTo(String value) {
            addCriterion("clocal <=", value, "clocal");
            return (Criteria) this;
        }

        public Criteria andClocalLike(String value) {
            addCriterion("clocal like", value, "clocal");
            return (Criteria) this;
        }

        public Criteria andClocalNotLike(String value) {
            addCriterion("clocal not like", value, "clocal");
            return (Criteria) this;
        }

        public Criteria andClocalIn(List<String> values) {
            addCriterion("clocal in", values, "clocal");
            return (Criteria) this;
        }

        public Criteria andClocalNotIn(List<String> values) {
            addCriterion("clocal not in", values, "clocal");
            return (Criteria) this;
        }

        public Criteria andClocalBetween(String value1, String value2) {
            addCriterion("clocal between", value1, value2, "clocal");
            return (Criteria) this;
        }

        public Criteria andClocalNotBetween(String value1, String value2) {
            addCriterion("clocal not between", value1, value2, "clocal");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table commute
     *
     * @mbg.generated do_not_delete_during_merge Mon Feb 08 11:23:38 CST 2021
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table commute
     *
     * @mbg.generated Mon Feb 08 11:23:38 CST 2021
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}