package com.wzy.ems.pojo;

public class Dept {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dept.deptno
     *
     * @mbg.generated Mon Feb 08 11:23:38 CST 2021
     */
    private Integer deptno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dept.dname
     *
     * @mbg.generated Mon Feb 08 11:23:38 CST 2021
     */
    private String dname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dept.local
     *
     * @mbg.generated Mon Feb 08 11:23:38 CST 2021
     */
    private String local;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dept.deptno
     *
     * @return the value of dept.deptno
     *
     * @mbg.generated Mon Feb 08 11:23:38 CST 2021
     */
    public Integer getDeptno() {
        return deptno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dept.deptno
     *
     * @param deptno the value for dept.deptno
     *
     * @mbg.generated Mon Feb 08 11:23:38 CST 2021
     */
    public void setDeptno(Integer deptno) {
        this.deptno = deptno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dept.dname
     *
     * @return the value of dept.dname
     *
     * @mbg.generated Mon Feb 08 11:23:38 CST 2021
     */
    public String getDname() {
        return dname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dept.dname
     *
     * @param dname the value for dept.dname
     *
     * @mbg.generated Mon Feb 08 11:23:38 CST 2021
     */
    public void setDname(String dname) {
        this.dname = dname == null ? null : dname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dept.local
     *
     * @return the value of dept.local
     *
     * @mbg.generated Mon Feb 08 11:23:38 CST 2021
     */
    public String getLocal() {
        return local;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dept.local
     *
     * @param local the value for dept.local
     *
     * @mbg.generated Mon Feb 08 11:23:38 CST 2021
     */
    public void setLocal(String local) {
        this.local = local == null ? null : local.trim();
    }
}