package com.wzy.ems.pojo;

import java.util.Date;

public class Forum {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column forum.forumid
     *
     * @mbg.generated Mon Feb 08 11:23:38 CST 2021
     */
    private Integer forumid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column forum.content
     *
     * @mbg.generated Mon Feb 08 11:23:38 CST 2021
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column forum.F_time
     *
     * @mbg.generated Mon Feb 08 11:23:38 CST 2021
     */
    private Date fTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column forum.eid
     *
     * @mbg.generated Mon Feb 08 11:23:38 CST 2021
     */
    private Integer eid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column forum.forumid
     *
     * @return the value of forum.forumid
     *
     * @mbg.generated Mon Feb 08 11:23:38 CST 2021
     */
    public Integer getForumid() {
        return forumid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column forum.forumid
     *
     * @param forumid the value for forum.forumid
     *
     * @mbg.generated Mon Feb 08 11:23:38 CST 2021
     */
    public void setForumid(Integer forumid) {
        this.forumid = forumid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column forum.content
     *
     * @return the value of forum.content
     *
     * @mbg.generated Mon Feb 08 11:23:38 CST 2021
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column forum.content
     *
     * @param content the value for forum.content
     *
     * @mbg.generated Mon Feb 08 11:23:38 CST 2021
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column forum.F_time
     *
     * @return the value of forum.F_time
     *
     * @mbg.generated Mon Feb 08 11:23:38 CST 2021
     */
    public Date getfTime() {
        return fTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column forum.F_time
     *
     * @param fTime the value for forum.F_time
     *
     * @mbg.generated Mon Feb 08 11:23:38 CST 2021
     */
    public void setfTime(Date fTime) {
        this.fTime = fTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column forum.eid
     *
     * @return the value of forum.eid
     *
     * @mbg.generated Mon Feb 08 11:23:38 CST 2021
     */
    public Integer getEid() {
        return eid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column forum.eid
     *
     * @param eid the value for forum.eid
     *
     * @mbg.generated Mon Feb 08 11:23:38 CST 2021
     */
    public void setEid(Integer eid) {
        this.eid = eid;
    }
}