package com.wzy.ems.pojo;

public class RoleSources {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_sources.rsid
     *
     * @mbg.generated Mon Feb 08 11:23:38 CST 2021
     */
    private Integer rsid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_sources.rsdis
     *
     * @mbg.generated Mon Feb 08 11:23:38 CST 2021
     */
    private String rsdis;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_sources.resources_fk
     *
     * @mbg.generated Mon Feb 08 11:23:38 CST 2021
     */
    private Integer resourcesFk;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_sources.role_fk
     *
     * @mbg.generated Mon Feb 08 11:23:38 CST 2021
     */
    private Integer roleFk;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_sources.rsid
     *
     * @return the value of role_sources.rsid
     *
     * @mbg.generated Mon Feb 08 11:23:38 CST 2021
     */
    public Integer getRsid() {
        return rsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_sources.rsid
     *
     * @param rsid the value for role_sources.rsid
     *
     * @mbg.generated Mon Feb 08 11:23:38 CST 2021
     */
    public void setRsid(Integer rsid) {
        this.rsid = rsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_sources.rsdis
     *
     * @return the value of role_sources.rsdis
     *
     * @mbg.generated Mon Feb 08 11:23:38 CST 2021
     */
    public String getRsdis() {
        return rsdis;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_sources.rsdis
     *
     * @param rsdis the value for role_sources.rsdis
     *
     * @mbg.generated Mon Feb 08 11:23:38 CST 2021
     */
    public void setRsdis(String rsdis) {
        this.rsdis = rsdis == null ? null : rsdis.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_sources.resources_fk
     *
     * @return the value of role_sources.resources_fk
     *
     * @mbg.generated Mon Feb 08 11:23:38 CST 2021
     */
    public Integer getResourcesFk() {
        return resourcesFk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_sources.resources_fk
     *
     * @param resourcesFk the value for role_sources.resources_fk
     *
     * @mbg.generated Mon Feb 08 11:23:38 CST 2021
     */
    public void setResourcesFk(Integer resourcesFk) {
        this.resourcesFk = resourcesFk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_sources.role_fk
     *
     * @return the value of role_sources.role_fk
     *
     * @mbg.generated Mon Feb 08 11:23:38 CST 2021
     */
    public Integer getRoleFk() {
        return roleFk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_sources.role_fk
     *
     * @param roleFk the value for role_sources.role_fk
     *
     * @mbg.generated Mon Feb 08 11:23:38 CST 2021
     */
    public void setRoleFk(Integer roleFk) {
        this.roleFk = roleFk;
    }
}