package com.wzy.ems.pojo;

import java.util.Date;

public class Work {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work.workid
     *
     * @mbg.generated Mon Feb 08 11:23:38 CST 2021
     */
    private Integer workid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work.eid
     *
     * @mbg.generated Mon Feb 08 11:23:38 CST 2021
     */
    private Integer eid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work.temperature
     *
     * @mbg.generated Mon Feb 08 11:23:38 CST 2021
     */
    private String temperature;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column work.W_time
     *
     * @mbg.generated Mon Feb 08 11:23:38 CST 2021
     */
    private Date wTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work.workid
     *
     * @return the value of work.workid
     *
     * @mbg.generated Mon Feb 08 11:23:38 CST 2021
     */
    public Integer getWorkid() {
        return workid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work.workid
     *
     * @param workid the value for work.workid
     *
     * @mbg.generated Mon Feb 08 11:23:38 CST 2021
     */
    public void setWorkid(Integer workid) {
        this.workid = workid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work.eid
     *
     * @return the value of work.eid
     *
     * @mbg.generated Mon Feb 08 11:23:38 CST 2021
     */
    public Integer getEid() {
        return eid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work.eid
     *
     * @param eid the value for work.eid
     *
     * @mbg.generated Mon Feb 08 11:23:38 CST 2021
     */
    public void setEid(Integer eid) {
        this.eid = eid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work.temperature
     *
     * @return the value of work.temperature
     *
     * @mbg.generated Mon Feb 08 11:23:38 CST 2021
     */
    public String getTemperature() {
        return temperature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work.temperature
     *
     * @param temperature the value for work.temperature
     *
     * @mbg.generated Mon Feb 08 11:23:38 CST 2021
     */
    public void setTemperature(String temperature) {
        this.temperature = temperature == null ? null : temperature.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column work.W_time
     *
     * @return the value of work.W_time
     *
     * @mbg.generated Mon Feb 08 11:23:38 CST 2021
     */
    public Date getwTime() {
        return wTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column work.W_time
     *
     * @param wTime the value for work.W_time
     *
     * @mbg.generated Mon Feb 08 11:23:38 CST 2021
     */
    public void setwTime(Date wTime) {
        this.wTime = wTime;
    }
}