package com.wzy.ems.mapper;

import com.wzy.ems.pojo.EmpRole;
import com.wzy.ems.pojo.EmpRoleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface EmpRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emp_role
     *
     * @mbg.generated Mon Feb 08 11:23:38 CST 2021
     */
    long countByExample(EmpRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emp_role
     *
     * @mbg.generated Mon Feb 08 11:23:38 CST 2021
     */
    int deleteByExample(EmpRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emp_role
     *
     * @mbg.generated Mon Feb 08 11:23:38 CST 2021
     */
    int deleteByPrimaryKey(Integer erid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emp_role
     *
     * @mbg.generated Mon Feb 08 11:23:38 CST 2021
     */
    int insert(EmpRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emp_role
     *
     * @mbg.generated Mon Feb 08 11:23:38 CST 2021
     */
    int insertSelective(EmpRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emp_role
     *
     * @mbg.generated Mon Feb 08 11:23:38 CST 2021
     */
    List<EmpRole> selectByExample(EmpRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emp_role
     *
     * @mbg.generated Mon Feb 08 11:23:38 CST 2021
     */
    EmpRole selectByPrimaryKey(Integer erid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emp_role
     *
     * @mbg.generated Mon Feb 08 11:23:38 CST 2021
     */
    int updateByExampleSelective(@Param("record") EmpRole record, @Param("example") EmpRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emp_role
     *
     * @mbg.generated Mon Feb 08 11:23:38 CST 2021
     */
    int updateByExample(@Param("record") EmpRole record, @Param("example") EmpRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emp_role
     *
     * @mbg.generated Mon Feb 08 11:23:38 CST 2021
     */
    int updateByPrimaryKeySelective(EmpRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emp_role
     *
     * @mbg.generated Mon Feb 08 11:23:38 CST 2021
     */
    int updateByPrimaryKey(EmpRole record);
}