package com.wzy.ems.mapper;

import com.wzy.ems.pojo.RoleSources;
import com.wzy.ems.pojo.RoleSourcesExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RoleSourcesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_sources
     *
     * @mbg.generated Mon Feb 08 11:23:38 CST 2021
     */
    long countByExample(RoleSourcesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_sources
     *
     * @mbg.generated Mon Feb 08 11:23:38 CST 2021
     */
    int deleteByExample(RoleSourcesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_sources
     *
     * @mbg.generated Mon Feb 08 11:23:38 CST 2021
     */
    int deleteByPrimaryKey(Integer rsid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_sources
     *
     * @mbg.generated Mon Feb 08 11:23:38 CST 2021
     */
    int insert(RoleSources record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_sources
     *
     * @mbg.generated Mon Feb 08 11:23:38 CST 2021
     */
    int insertSelective(RoleSources record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_sources
     *
     * @mbg.generated Mon Feb 08 11:23:38 CST 2021
     */
    List<RoleSources> selectByExample(RoleSourcesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_sources
     *
     * @mbg.generated Mon Feb 08 11:23:38 CST 2021
     */
    RoleSources selectByPrimaryKey(Integer rsid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_sources
     *
     * @mbg.generated Mon Feb 08 11:23:38 CST 2021
     */
    int updateByExampleSelective(@Param("record") RoleSources record, @Param("example") RoleSourcesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_sources
     *
     * @mbg.generated Mon Feb 08 11:23:38 CST 2021
     */
    int updateByExample(@Param("record") RoleSources record, @Param("example") RoleSourcesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_sources
     *
     * @mbg.generated Mon Feb 08 11:23:38 CST 2021
     */
    int updateByPrimaryKeySelective(RoleSources record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_sources
     *
     * @mbg.generated Mon Feb 08 11:23:38 CST 2021
     */
    int updateByPrimaryKey(RoleSources record);
}