package com.wzy.ems.mapper;

import com.wzy.ems.pojo.Sources;
import com.wzy.ems.pojo.SourcesExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SourcesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sources
     *
     * @mbg.generated Mon Feb 08 11:23:38 CST 2021
     */
    long countByExample(SourcesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sources
     *
     * @mbg.generated Mon Feb 08 11:23:38 CST 2021
     */
    int deleteByExample(SourcesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sources
     *
     * @mbg.generated Mon Feb 08 11:23:38 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sources
     *
     * @mbg.generated Mon Feb 08 11:23:38 CST 2021
     */
    int insert(Sources record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sources
     *
     * @mbg.generated Mon Feb 08 11:23:38 CST 2021
     */
    int insertSelective(Sources record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sources
     *
     * @mbg.generated Mon Feb 08 11:23:38 CST 2021
     */
    List<Sources> selectByExample(SourcesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sources
     *
     * @mbg.generated Mon Feb 08 11:23:38 CST 2021
     */
    Sources selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sources
     *
     * @mbg.generated Mon Feb 08 11:23:38 CST 2021
     */
    int updateByExampleSelective(@Param("record") Sources record, @Param("example") SourcesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sources
     *
     * @mbg.generated Mon Feb 08 11:23:38 CST 2021
     */
    int updateByExample(@Param("record") Sources record, @Param("example") SourcesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sources
     *
     * @mbg.generated Mon Feb 08 11:23:38 CST 2021
     */
    int updateByPrimaryKeySelective(Sources record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sources
     *
     * @mbg.generated Mon Feb 08 11:23:38 CST 2021
     */
    int updateByPrimaryKey(Sources record);
}